services:
  - type: web
    name: eb-payments-api
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: RUN_MIGRATIONS
        value: "true"
      - key: PORT
        value: "3001"
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: WEB_URL
        sync: false
