export interface Country {
  code: string;
  name: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AU', name: 'Австралия' },
  { code: 'AT', name: 'Австрия' },
  { code: 'AZ', name: 'Азербайджан' },
  { code: 'AL', name: 'Албания' },
  { code: 'DZ', name: 'Алжир' },
  { code: 'AR', name: 'Аргентина' },
  { code: 'AM', name: 'Армения' },
  { code: 'BD', name: 'Бангладеш' },
  { code: 'BY', name: 'Беларусь' },
  { code: 'BE', name: 'Бельгия' },
  { code: 'BG', name: 'Болгария' },
  { code: 'BR', name: 'Бразилия' },
  { code: 'GB', name: 'Великобритания' },
  { code: 'HU', name: 'Венгрия' },
  { code: 'VN', name: 'Вьетнам' },
  { code: 'DE', name: 'Германия' },
  { code: 'GR', name: 'Греция' },
  { code: 'GE', name: 'Грузия' },
  { code: 'DK', name: 'Дания' },
  { code: 'EG', name: 'Египет' },
  { code: 'IL', name: 'Израиль' },
  { code: 'IN', name: 'Индия' },
  { code: 'ID', name: 'Индонезия' },
  { code: 'IE', name: 'Ирландия' },
  { code: 'IS', name: 'Исландия' },
  { code: 'ES', name: 'Испания' },
  { code: 'IT', name: 'Италия' },
  { code: 'KZ', name: 'Казахстан' },
  { code: 'CA', name: 'Канада' },
  { code: 'QA', name: 'Катар' },
  { code: 'KE', name: 'Кения' },
  { code: 'CY', name: 'Кипр' },
  { code: 'CN', name: 'Китай' },
  { code: 'CO', name: 'Колумбия' },
  { code: 'KR', name: 'Корея (Южная)' },
  { code: 'KG', name: 'Кыргызстан' },
  { code: 'LV', name: 'Латвия' },
  { code: 'LT', name: 'Литва' },
  { code: 'LU', name: 'Люксембург' },
  { code: 'MY', name: 'Малайзия' },
  { code: 'MT', name: 'Мальта' },
  { code: 'MA', name: 'Марокко' },
  { code: 'MX', name: 'Мексика' },
  { code: 'MD', name: 'Молдова' },
  { code: 'NL', name: 'Нидерланды' },
  { code: 'NZ', name: 'Новая Зеландия' },
  { code: 'NO', name: 'Норвегия' },
  { code: 'AE', name: 'ОАЭ' },
  { code: 'PK', name: 'Пакистан' },
  { code: 'PL', name: 'Польша' },
  { code: 'PT', name: 'Португалия' },
  { code: 'RU', name: 'Россия' },
  { code: 'RO', name: 'Румыния' },
  { code: 'SA', name: 'Саудовская Аравия' },
  { code: 'RS', name: 'Сербия' },
  { code: 'SG', name: 'Сингапур' },
  { code: 'SK', name: 'Словакия' },
  { code: 'SI', name: 'Словения' },
  { code: 'US', name: 'США' },
  { code: 'TJ', name: 'Таджикистан' },
  { code: 'TH', name: 'Таиланд' },
  { code: 'TW', name: 'Тайвань' },
  { code: 'TR', name: 'Турция' },
  { code: 'UZ', name: 'Узбекистан' },
  { code: 'UA', name: 'Украина' },
  { code: 'PH', name: 'Филиппины' },
  { code: 'FI', name: 'Финляндия' },
  { code: 'FR', name: 'Франция' },
  { code: 'HR', name: 'Хорватия' },
  { code: 'CZ', name: 'Чехия' },
  { code: 'CL', name: 'Чили' },
  { code: 'CH', name: 'Швейцария' },
  { code: 'SE', name: 'Швеция' },
  { code: 'EC', name: 'Эквадор' },
  { code: 'EE', name: 'Эстония' },
  { code: 'ZA', name: 'ЮАР' },
  { code: 'JP', name: 'Япония' },
].sort((a, b) => a.name.localeCompare(b.name, 'ru'));
